version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 3030:3030
    volumes:
      - .:/app
    networks:
      - cache-network
    environment:
      - VIRTUAL_HOST=my.home.local
      - VIRTUAL_PORT=3030
    restart: always
    command: >
      sh -c "python manage.py runserver 0.0.0.0:3030"
    depends_on:
      - celery

  redis:
    image: "redis:alpine"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - cache-network

  celery:
    image: smart_home_app
    volumes:
      - .:/app
    networks:
      - cache-network
    depends_on:
      - redis
    command: >
      sh -c "python -m celery -A config worker -l INFO"

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - DEFAULT_HOST=my.home.local
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      #- ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - cache-network
    depends_on:
      - app

networks:
  cache-network:
    driver: bridge
