version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 3030:3030
    volumes:
      - .:/app
    networks:
      - cache-network
    restart: always
    command: >
      sh -c "python manage.py runserver 0.0.0.0:3030"
    depends_on:
      - celery

  redis:
    image: "redis:alpine"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - cache-network

  celery:
    image: todo-django-app
    volumes:
      - .:/app
    networks:
      - cache-network
    depends_on:
      - redis
    command: >
      sh -c "python -m celery -A config worker -l INFO"


networks:
  cache-network:
    driver: bridge
