"""Store Views"""

# Libraries
from itertools import product
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.conf import settings
from django.db.models import Q
from django.core.paginator import Paginator
from djmoney.money import Money

# Modules
from . import models, forms
from products import models as product_models


class StoreListView(LoginRequiredMixin, generic.list.ListView):
    model = models.Store
    paginate_by = settings.PAGINATION_LIMIT
    template_name = 'stores/index.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super(StoreListView, self).get_queryset(*args, **kwargs)
        queryset = queryset.filter(enabled=True)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(StoreListView, self).get_context_data(*args, **kwargs)
        context['count'] = self.get_queryset().count()
        return context


class StoreNewView(LoginRequiredMixin, generic.edit.FormView):
    template_name = 'stores/edit.html'
    form_class = forms.StoreForm
    success_url = 'stores:list'

    def get_context_data(self, **kwargs):
        """Get Context Data"""
        # context = super(StoreNewView, self).get_context_data(**kwargs)
        context = {}
        context['mode'] = 'Save'
        context['form'] = self.form_class(self.request.user)
        return context

    def form_valid(self, form):
        self.object = form.save(
            commit=False,
            **{'user': self.request.user}
        )
        self.object.save()
        return redirect(self.get_success_url())


class StoreEditView(LoginRequiredMixin, generic.edit.UpdateView):
    model = models.Store
    form_class = forms.StoreForm
    template_name = 'stores/edit.html'
    success_url = 'stores:list'

    def get_context_data(self, **kwargs):
        """Get Context Data"""
        context = super(StoreEditView, self).get_context_data(**kwargs)
        context['mode'] = 'Update'
        return context

    def form_valid(self, form, *args, **kwargs):
        """Get Form Valid"""
        self.object = form.save(commit=False, updated=True)
        self.object.save()

        return redirect(
            self.get_success_url()
        )


class DetailStoreView(LoginRequiredMixin, generic.detail.DetailView):
    """Detail Board View"""
    model = models.Store
    template_name = 'stores/detail.html'

    def queryset_list(self, pk):
        return models.StoreProduct.objects.filter(enabled=True, store=pk)

    def queryset_products(self, pk, query = None):
        my_list = [x.product.pk for x in self.queryset_list(pk)]
        data = (
            product_models.Product.objects.filter(
                enabled=True,
            )
            .exclude(pk__in=my_list)
        )
        if query:
            data = data.filter(
                Q(name__icontains=query) | Q(description__icontains=query)
            )
        return data

    def paginate(self, data: list):
        return Paginator(data, settings.PAGINATION_LIMIT)

    def get_context_data(self, *args, **kwargs):
        """Context generated by detail board"""
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get("q") or None

        products = self.paginate(self.queryset_products(context['store'], query))
        count_products = products.count
        products = products.page(self.request.GET.get("page_products") or 1)

        items = self.paginate(self.queryset_list(context['store']))
        count_items = items.count
        items = items.page(self.request.GET.get("page_items") or 1)

        context['items'] = items
        context['products'] = products
        context["count_products"] = count_products
        context["form_item"] = forms.StoreProductForm(context['store'])
        context["count_items"] = count_items
        context["search"] = query
        return context


@login_required
def delete_store(request, pk):
    model = models.Store
    store = get_object_or_404(model, pk=pk)
    store.enabled = False
    store.save()
    return redirect("stores:list")


@login_required
def add_product_to_store(request, pk):
    form = forms.StoreProductCompleteForm(request.POST)
    if form.is_valid:
        object = form.save(
            commit=False,
            user=request.user,
        )
        object.save()
    return redirect("stores:detail", pk=pk)


@login_required
def edit_product_to_store(request, pk, pk_item):
    model = models.StoreProduct
    item = get_object_or_404(model, pk=pk_item)
    item.description = request.POST.get("description")
    item.price = Money(request.POST.get("price_0"), request.POST.get("price_1"))
    item.save()
    return redirect("stores:detail", pk=pk)


@login_required
def delete_product_to_store(request, pk, pk_item):
    model = models.StoreProduct
    item = get_object_or_404(model, pk=pk_item)
    item.enabled = False
    item.save()
    return redirect("stores:detail", pk=pk)
