# Generated by Django 3.2.3 on 2023-01-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kindle_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Kindle Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
