# Generated by Django 3.2.3 on 2022-09-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryflow',
            name='type_flow',
            field=models.CharField(choices=[('PE', 'Passive Expenditure'), ('AE', 'Active Expenditure'), ('PI', 'Passive Income'), ('AI', 'Active Income')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
