# Generated by Django 3.2.3 on 2022-09-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0002_categoryflow_type_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryflow',
            name='state_flow',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('P', 'Passive')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='categoryflow',
            name='type_flow',
            field=models.CharField(choices=[('E', 'Expenditure'), ('I', 'Income')], max_length=3),
        ),
    ]
