# Generated by Django 3.2.3 on 2022-09-11 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0004_flowmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowmoney',
            name='date_flow',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 20, 55, 10, 47861)),
        ),
    ]
