# Generated by Django 3.2.3 on 2022-09-12 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0006_auto_20220911_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmoney',
            name='date_flow',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 10, 54, 35, 289384)),
        ),
    ]
