# Generated by Django 3.2.3 on 2022-09-18 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0013_alter_flowmoney_date_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmoney',
            name='date_flow',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
