# Generated by Django 3.2.3 on 2023-01-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0017_auto_20221226_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmoney',
            name='date_flow',
            field=models.DateField(blank=True, default='2023-01-07'),
        ),
    ]
