# Generated by Django 3.2.3 on 2023-01-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0021_alter_flowmoney_date_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmoney',
            name='date_flow',
            field=models.DateField(blank=True, default='2023-01-22'),
        ),
    ]
