# Generated by Django 3.2.3 on 2022-02-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMangaAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('anime', 'anime'), ('manga', 'manga'), ('person', 'person'), ('character', 'character')], default='anime', max_length=10, verbose_name='Type')),
                ('uid_anime', models.PositiveIntegerField(verbose_name='Id Anime')),
                ('url_anime', models.CharField(max_length=70, verbose_name='Url Anime')),
                ('url_image', models.CharField(max_length=90, verbose_name='Url Image')),
            ],
        ),
    ]
