# Generated by Django 3.2.3 on 2022-02-06 17:17

from django.db import migrations, models
import to_buy.enums


class Migration(migrations.Migration):

    dependencies = [
        ('to_buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtobuy',
            name='priority',
            field=models.CharField(choices=[(to_buy.enums.Priority['HIGH'], 'high'), (to_buy.enums.Priority['MEDIUM'], 'medium'), (to_buy.enums.Priority['LOW'], 'low')], default='low', max_length=40),
        ),
    ]
