# Generated by Django 3.2.3 on 2022-02-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_buy', '0002_alter_listtobuy_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisttobuy',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listtobuy',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=40),
        ),
    ]
