# Generated by Django 3.2.3 on 2022-02-20 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_storeproduct_price'),
        ('to_buy', '0003_auto_20220206_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisttobuy',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_list_store', to='stores.store'),
            preserve_default=False,
        ),
    ]
