# Generated by Django 3.2.3 on 2022-02-20 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_storeproduct_price'),
        ('to_buy', '0004_itemlisttobuy_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisttobuy',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_list_store_product', to='stores.storeproduct'),
        ),
    ]
