# Generated by Django 3.2.3 on 2022-02-13 22:49

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='4.599011638118746,-74.08252716064453', max_length=63),
        ),
    ]
