# Generated by Django 3.2.3 on 2022-02-05 22:09

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
